### ISSUE TITLE
Error 404 on clicking github icon in contact me section

### ISSUE THREAD

**Issue by vinayak5002** [Jegadit/Portfolio_v1#1]
https://github.com/Jegadit/Portfolio_v1/blob/d030bc84b7fe2d6d838af9ba77e1c9920e6b9b29/index.html#L98

Username mentioned ```<a>``` ```href``` is different from your actual github username

update href link to solve error 404

**Comment by RulerOfEternalNight** [comment]
The issue has been rectified.
Thank you
